server:
    port: 9901
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://192.168.1.203:33306/pdd?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


